### PR TITLE
update request document and finished revert function

### PR DESCRIPTION
**Pull request by Jinkunxiang**

### CODE REVIEW

**Comment by likexin0304** [comment]
Did you modify the delete function when you added revert function?

**Comment by Jinkunxiang** [comment]
ooooops! I forgot it, I will try to modify it later.

**Comment by likexin0304** [comment]
cool

**Comment by Jinkunxiang** [comment]
The function have already be modified

**Comment by likexin0304** [comment]
Could you add some comments for this new function? Thank you

**Comment by Jinkunxiang** [comment]
got it

**Comment by Jinkunxiang** [comment]
I'll do it later

**Comment by Jinkunxiang** [comment]
I'll do it later

**Comment by Jinkunxiang** [comment]
comments are already added

**Comment by likexin0304** [comment]
Thank you

**Pull request merged**
