### PR TITLE
Fix Rename Bug

### PR DESCRIPTION
**Pull request by Jinkunxiang**

### CODE REVIEW

**Comment by likexin0304** [comment]
Could you double check with this bug? The Desktop and Moblie clients found that there still is a bug.  Thank you

**Comment by Jinkunxiang** [comment]
I will double check it. And please do more test, it's may be caused by changing the implementation between the new and old version.

**Comment by likexin0304** [comment]
sure.

**Comment by likexin0304** [comment]
after testing with the desktop client, there is no bug for rename function.  great

**Pull request merged**
